# circleci pls make these inheritable

version: 2
jobs:
  "3.6":
    docker:
      - image: python:3.6

    # these are all basically the same
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            pip install -e .[tests]

      - run:
          name: Run tests
          command: |
            bash .circleci/runtests.sh

  "3.7":
    docker:
      - image: python:3.7

    # these are all basically the same
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            pip install -e .[tests]

      - run:
          name: Run tests
          command: |
            bash .circleci/runtests.sh



workflows:
  version: 2
  build_and_test:
    jobs:
      - "3.6"
      - "3.7"
